name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      # TODO 2
      # 현재 Repository로 Docker Image를 빌드하고,
      # <Docker Hub username>/fastapi-demo-hello-world:latest 로 push하세요.
      - name: Buil and push Docker Image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-demo-hello-world:latest

      # TODO 3
      # EC2에 SSH로 접속한 뒤
      # 1. Docker Hub의 latest Image를 pull하고
      # 2. 기존 fastapi-demo Container를 제거하고
      # 3. 새 Container를 EC2의 80번 포트와 Container의 8000번 포트를 연결해 실행하세요.
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-demo-hello-world:latest
            sudo docker rm -f fastapi-demo || true
            sudo docker run -d \
              --name fastapi-demo \
              --restart unless-stopped \
              -p 80:8000 \
              ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-demo-hello-world:latest